events {
    worker_connections     1024;
}

http {
    include /etc/nginx/mime.types;

    sendfile on;

    index index.html;

    client_max_body_size 20M;

    server {
        listen 80;
        listen [::]:80;

        server_name localhost;

        root /usr/share/nginx/html;
        gzip_static on;

        location / {
            try_files $uri $uri/ /index.html;
        }
    }

}